# Práctica 2: Lectura y manipulación de datos con Pandas

En esta práctica aprenderás los conceptos básicos de **Pandas**, la librería más utilizada en Python para el análisis de datos.

**Temas:**
- ¿Qué es Pandas?
- Series y DataFrames
- Lectura de datos desde archivos
- Exploración de datos
- Selección y filtrado
- Operaciones básicas
- Ejercicio práctico

## 1. ¿Qué es Pandas?

**Pandas** es una librería de Python diseñada para la manipulación y el análisis de datos estructurados (tablas, hojas de cálculo, bases de datos, etc.).

Sus dos estructuras principales son:

| Estructura | Descripción |
|---|---|
| `Series` | Una columna de datos (como un vector o una lista con etiquetas). |
| `DataFrame` | Una tabla completa con filas y columnas (como una hoja de Excel). |

Para usarla, primero hay que importarla:

In [2]:
import pandas as pd  # "pd" es la convención estándar
print(f"Versión de Pandas: {pd.__version__}")

Versión de Pandas: 3.0.1

## 2. Series y DataFrames

### Series
Una `Series` es como una lista con índices (etiquetas).

In [3]:
# Crear una Serie desde una lista
notas = pd.Series([85, 92, 78, 95, 88], name="Notas")
print(notas)
print(f"\nTipo: {type(notas)}")

# Crear una Serie con índices personalizados
notas_estudiantes = pd.Series(
    [85, 92, 78, 95, 88],
    index=["Ana", "Luis", "María", "Carlos", "Sofía"],
    name="Notas"
)
print("\nNotas con nombres:")
print(notas_estudiantes)

# Acceder a un valor por su índice
print(f"\nNota de Ana: {notas_estudiantes['Ana']}")

0    85
1    92
2    78
3    95
4    88
Name: Notas, dtype: int64

Tipo: <class 'pandas.Series'>

Notas con nombres:
Ana       85
Luis      92
María     78
Carlos    95
Sofía     88
Name: Notas, dtype: int64

Nota de Ana: 85

### DataFrame
Un `DataFrame` es una tabla con filas y columnas. Se puede crear desde un diccionario.

In [4]:
# Crear un DataFrame desde un diccionario
datos = {
    "Nombre": ["Ana", "Luis", "María", "Carlos", "Sofía"],
    "Edad": [21, 23, 22, 24, 20],
    "Nota": [85, 92, 78, 95, 88],
    "Ciudad": ["Bogotá", "Medellín", "Cali", "Bogotá", "Medellín"]
}

df = pd.DataFrame(datos)
print("DataFrame:")
df

DataFrame:

   Nombre  Edad  Nota    Ciudad
0     Ana    21    85    Bogotá
1    Luis    23    92  Medellín
2   María    22    78      Cali
3  Carlos    24    95    Bogotá
4   Sofía    20    88  Medellín

## 3. Lectura de datos desde archivos

Pandas puede leer datos de múltiples formatos:

| Función | Formato |
|---|---|
| `pd.read_csv()` | Archivos CSV |
| `pd.read_excel()` | Archivos Excel (.xlsx) |
| `pd.read_json()` | Archivos JSON |
| `pd.read_sql()` | Bases de datos SQL |

Para este ejemplo, guardaremos nuestro DataFrame como CSV y luego lo leeremos.

In [5]:
# Guardar el DataFrame como archivo CSV
df.to_csv("estudiantes.csv", index=False)
print("Archivo 'estudiantes.csv' guardado.")

# Leer el archivo CSV
df_leido = pd.read_csv("estudiantes.csv")
print("\nDataFrame leído desde CSV:")
df_leido

Archivo 'estudiantes.csv' guardado.

DataFrame leído desde CSV:

   Nombre  Edad  Nota    Ciudad
0     Ana    21    85    Bogotá
1    Luis    23    92  Medellín
2   María    22    78      Cali
3  Carlos    24    95    Bogotá
4   Sofía    20    88  Medellín

## 4. Exploración de datos

Cuando recibes datos nuevos, lo primero es explorarlos para entender su estructura.

In [6]:
# Ver las primeras filas
print("Primeras 3 filas:")
print(df.head(3))

# Ver las últimas filas
print("\nÚltimas 2 filas:")
print(df.tail(2))

# Dimensiones del DataFrame (filas, columnas)
print(f"\nDimensiones: {df.shape}")
print(f"Filas: {df.shape[0]}, Columnas: {df.shape[1]}")

# Nombres de las columnas
print(f"\nColumnas: {list(df.columns)}")

# Tipos de datos de cada columna
print("\nTipos de datos:")
print(df.dtypes)

Primeras 3 filas:
  Nombre  Edad  Nota    Ciudad
0    Ana    21    85    Bogotá
1   Luis    23    92  Medellín
2  María    22    78      Cali

Últimas 2 filas:
   Nombre  Edad  Nota    Ciudad
3  Carlos    24    95    Bogotá
4   Sofía    20    88  Medellín

Dimensiones: (5, 4)
Filas: 5, Columnas: 4

Columnas: ['Nombre', 'Edad', 'Nota', 'Ciudad']

Tipos de datos:
Nombre      str
Edad      int64
Nota      int64
Ciudad      str
dtype: object

In [7]:
# Resumen de información general
print("Información del DataFrame:")
print(df.info())

# Estadísticas descriptivas de columnas numéricas
print("\nEstadísticas descriptivas:")
df.describe()

Información del DataFrame:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  5 non-null      str
 1   Edad    5 non-null      int64
 2   Nota    5 non-null      int64
 3   Ciudad  5 non-null      str
dtypes: int64(2), str(2)
memory usage: 292.0 bytes
None

Estadísticas descriptivas:

            Edad       Nota
count   5.000000   5.000000
mean   22.000000  87.600000
std     1.581139   6.580274
min    20.000000  78.000000
25%    21.000000  85.000000
50%    22.000000  88.000000
75%    23.000000  92.000000
max    24.000000  95.000000

## 5. Selección y filtrado de datos

### Seleccionar columnas

In [8]:
# Seleccionar una sola columna (devuelve una Serie)
print("Columna 'Nombre':")
print(df["Nombre"])

# Seleccionar varias columnas (devuelve un DataFrame)
print("\nColumnas 'Nombre' y 'Nota':")
df[["Nombre", "Nota"]]

Columna 'Nombre':
0       Ana
1      Luis
2     María
3    Carlos
4     Sofía
Name: Nombre, dtype: str

Columnas 'Nombre' y 'Nota':

   Nombre  Nota
0     Ana    85
1    Luis    92
2   María    78
3  Carlos    95
4   Sofía    88

### Seleccionar filas con `iloc` y `loc`

- `iloc` → selección por **posición** (índice numérico)
- `loc` → selección por **etiqueta** (nombre del índice)

In [9]:
# Seleccionar la primera fila por posición
print("Primera fila (iloc):")
print(df.iloc[0])

# Seleccionar filas 1 a 3
print("\nFilas 1 a 3:")
print(df.iloc[1:4])

# Seleccionar fila y columna específica
print(f"\nNombre de la fila 2: {df.iloc[2, 0]}")
print(f"Nota de la fila 2: {df.iloc[2, 2]}")

Primera fila (iloc):
Nombre       Ana
Edad          21
Nota          85
Ciudad    Bogotá
Name: 0, dtype: object

Filas 1 a 3:
   Nombre  Edad  Nota    Ciudad
1    Luis    23    92  Medellín
2   María    22    78      Cali
3  Carlos    24    95    Bogotá

Nombre de la fila 2: María
Nota de la fila 2: 78

### Filtrar datos con condiciones

Puedes filtrar filas que cumplan una condición lógica.

In [10]:
# Estudiantes con nota mayor o igual a 90
print("Estudiantes con nota >= 90:")
aprobados = df[df["Nota"] >= 90]
print(aprobados)

# Estudiantes de Bogotá
print("\nEstudiantes de Bogotá:")
bogota = df[df["Ciudad"] == "Bogotá"]
print(bogota)

# Combinar condiciones: nota >= 85 Y edad < 23
print("\nNota >= 85 y edad < 23:")
filtro = df[(df["Nota"] >= 85) & (df["Edad"] < 23)]
print(filtro)

Estudiantes con nota >= 90:
   Nombre  Edad  Nota    Ciudad
1    Luis    23    92  Medellín
3  Carlos    24    95    Bogotá

Estudiantes de Bogotá:
   Nombre  Edad  Nota  Ciudad
0     Ana    21    85  Bogotá
3  Carlos    24    95  Bogotá

Nota >= 85 y edad < 23:
  Nombre  Edad  Nota    Ciudad
0    Ana    21    85    Bogotá
4  Sofía    20    88  Medellín

## 6. Operaciones básicas

### Agregar y eliminar columnas

In [11]:
# Agregar una nueva columna calculada
df["Aprobado"] = df["Nota"] >= 70
print("Con columna 'Aprobado':")
print(df)

# Agregar una columna con operación aritmética
df["Nota_sobre_100"] = df["Nota"] / 100
print("\nCon columna 'Nota_sobre_100':")
print(df)

# Eliminar una columna
df = df.drop(columns=["Nota_sobre_100"])
print("\nSin 'Nota_sobre_100':")
print(df)

Con columna 'Aprobado':
   Nombre  Edad  Nota    Ciudad  Aprobado
0     Ana    21    85    Bogotá      True
1    Luis    23    92  Medellín      True
2   María    22    78      Cali      True
3  Carlos    24    95    Bogotá      True
4   Sofía    20    88  Medellín      True

Con columna 'Nota_sobre_100':
   Nombre  Edad  Nota    Ciudad  Aprobado  Nota_sobre_100
0     Ana    21    85    Bogotá      True            0.85
1    Luis    23    92  Medellín      True            0.92
2   María    22    78      Cali      True            0.78
3  Carlos    24    95    Bogotá      True            0.95
4   Sofía    20    88  Medellín      True            0.88

Sin 'Nota_sobre_100':
   Nombre  Edad  Nota    Ciudad  Aprobado
0     Ana    21    85    Bogotá      True
1    Luis    23    92  Medellín      True
2   María    22    78      Cali      True
3  Carlos    24    95    Bogotá      True
4   Sofía    20    88  Medellín      True

### Ordenar datos

In [12]:
# Ordenar por nota (ascendente)
print("Ordenado por nota (menor a mayor):")
print(df.sort_values("Nota"))

# Ordenar por nota (descendente)
print("\nOrdenado por nota (mayor a menor):")
print(df.sort_values("Nota", ascending=False))

Ordenado por nota (menor a mayor):
   Nombre  Edad  Nota    Ciudad  Aprobado
2   María    22    78      Cali      True
0     Ana    21    85    Bogotá      True
4   Sofía    20    88  Medellín      True
1    Luis    23    92  Medellín      True
3  Carlos    24    95    Bogotá      True

Ordenado por nota (mayor a menor):
   Nombre  Edad  Nota    Ciudad  Aprobado
3  Carlos    24    95    Bogotá      True
1    Luis    23    92  Medellín      True
4   Sofía    20    88  Medellín      True
0     Ana    21    85    Bogotá      True
2   María    22    78      Cali      True

### Agrupar datos con `groupby`

Permite agrupar filas por una columna y calcular estadísticas por grupo.

In [13]:
# Promedio de nota por ciudad
print("Promedio de nota por ciudad:")
print(df.groupby("Ciudad")["Nota"].mean())

# Contar estudiantes por ciudad
print("\nEstudiantes por ciudad:")
print(df.groupby("Ciudad")["Nombre"].count())

# Múltiples estadísticas por grupo
print("\nEstadísticas de nota por ciudad:")
print(df.groupby("Ciudad")["Nota"].agg(["mean", "min", "max"]))

Promedio de nota por ciudad:
Ciudad
Bogotá      90.0
Cali        78.0
Medellín    90.0
Name: Nota, dtype: float64

Estudiantes por ciudad:
Ciudad
Bogotá      2
Cali        1
Medellín    2
Name: Nombre, dtype: int64

Estadísticas de nota por ciudad:
          mean  min  max
Ciudad
Bogotá    90.0   85   95
Cali      78.0   78   78
Medellín  90.0   88   92

## 7. Ejercicio práctico

**Ejercicio:** Dado el siguiente DataFrame de ventas, resuelve las preguntas:

1. ¿Cuántas filas y columnas tiene el DataFrame?
2. Filtra las ventas mayores a $500
3. ¿Cuál es el total de ventas por producto?
4. Ordena el DataFrame por monto de venta de mayor a menor

In [14]:
# Datos de ejemplo
ventas = pd.DataFrame({
    "Producto": ["Laptop", "Mouse", "Teclado", "Monitor", "Laptop", "Mouse", "Monitor"],
    "Cantidad": [2, 10, 5, 3, 1, 8, 2],
    "Precio_unitario": [800, 25, 45, 350, 800, 25, 350],
    "Vendedor": ["Pedro", "Ana", "Ana", "Pedro", "Ana", "Pedro", "Ana"]
})

# Agregar columna de venta total
ventas["Venta_total"] = ventas["Cantidad"] * ventas["Precio_unitario"]
ventas

  Producto  Cantidad  Precio_unitario Vendedor  Venta_total
0   Laptop         2              800    Pedro         1600
1    Mouse        10               25      Ana          250
2  Teclado         5               45      Ana          225
3  Monitor         3              350    Pedro         1050
4   Laptop         1              800      Ana          800
5    Mouse         8               25    Pedro          200
6  Monitor         2              350      Ana          700

In [15]:
# Escribe tu solución aquí:

### Solución

In [16]:
# 1. Dimensiones del DataFrame
print(f"Dimensiones: {ventas.shape} → {ventas.shape[0]} filas, {ventas.shape[1]} columnas")

# 2. Ventas mayores a $500
print("\nVentas mayores a $500:")
print(ventas[ventas["Venta_total"] > 500])

# 3. Total de ventas por producto
print("\nTotal de ventas por producto:")
print(ventas.groupby("Producto")["Venta_total"].sum())

# 4. Ordenar por venta total (mayor a menor)
print("\nOrdenado por venta total:")
print(ventas.sort_values("Venta_total", ascending=False))

Dimensiones: (7, 5) → 7 filas, 5 columnas

Ventas mayores a $500:
  Producto  Cantidad  Precio_unitario Vendedor  Venta_total
0   Laptop         2              800    Pedro         1600
3  Monitor         3              350    Pedro         1050
4   Laptop         1              800      Ana          800
6  Monitor         2              350      Ana          700

Total de ventas por producto:
Producto
Laptop     2400
Monitor    1750
Mouse       450
Teclado     225
Name: Venta_total, dtype: int64

Ordenado por venta total:
  Producto  Cantidad  Precio_unitario Vendedor  Venta_total
0   Laptop         2              800    Pedro         1600
3  Monitor         3              350    Pedro         1050
4   Laptop         1              800      Ana          800
6  Monitor         2              350      Ana          700
1    Mouse        10               25      Ana          250
2  Teclado         5               45      Ana          225
5    Mouse         8               25    Pedro          200